name: JansParadise
version: "1.1"
main: jansparadise.jansparadise.JansParadise
api-version: 1.19
commands:
  heal:
    permission: permission.mod
  fly:
    permission: permission.mod
  feed:
  kit:
  sign:
  fix:
  uwu:
  invsee:
  spawn:
  ec:
  workbench:
    aliases: "wb"
  anvil:
  specialitems:
    aliases: "items"
  vanish:
    aliases: "v"
    permission: permission.mod
  rezepte:
    aliases: "recipes"
  rezept:
    aliases: "recipe"
  playerinfo:
  trash:
    aliases: "müll"
    permission: permission.mod
  xp:
  trade:
    aliases: "handel"
  modify:
    aliases: "modifizieren"
  cratestats:
    aliases: "cs"
  top:
  perks:
  infobar:
permissions:
  permission.mod:
    default: op