name: SciFi_Skirmish
version: "\u001B[35m Alpha 0.2.4"
main: plugin.Main
api-version: 1.19
commands:
  heal:
    permission: permission.mod
  kit:
  sign:
  fix:
  uwu:
  invsee:
  spawn:
  workbench:
    aliases: "wb"
  anvil:
  specialitems:
    aliases: "items"
  vanish:
    aliases: "v"
    permission: permission.mod
  stats:
  shop:
    aliases: 'laden'
  trash:
    aliases: "müll"
  xp:
    aliases: "handel"
  modify:
    aliases: "modifizieren"
  top:
  perks:
  infobar:
  crate:
    permission: permission.mod
  nightvision:
    aliases: ['nv', 'nachtsicht']
  setrank:
    permission: permission.mod
  safe:
    aliases: ['tr', 'tresor']
permissions:
  permission.mod:
    default: op