name: SciFi_Skirmish
version: "\u001B[35m Alpha 0.2.4 \u001B[0m"
main: plugin.Main
api-version: 1.19
commands:
  heal:
    permission: permission.mod
  kit:
  sign:
  fix:
  uwu:
  invsee:
  spawn:
  ec:
  workbench:
    aliases: "wb"
  anvil:
  specialitems:
    aliases: "items"
  vanish:
    aliases: "v"
    permission: permission.mod
  rezepte:
    aliases: "recipes"
  rezept:
    aliases: "recipe"
  stats:
  trash:
    aliases: "müll"
    permission: permission.mod
  xp:
    aliases: "handel"
  modify:
    aliases: "modifizieren"
  top:
  perks:
  infobar:
  crate:
    aliases: "spawnarmorstand"
    permission: permission.mod
  smithingtable:
    aliases: 'st'
permissions:
  permission.mod:
    default: op